apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: onyxdotapp/onyx-backend-cloud:v0.14.0-cloud.beta.21
          imagePullPolicy: IfNotPresent
          command:
            [
              "celery",
              "-A",
              "onyx.background.celery.versioned_apps.beat",
              "beat",
              "--loglevel=INFO",
            ]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onyx-secrets
                  key: redis_password
            - name: ONYX_VERSION
              value: "v0.11.0-cloud.beta.8"
          envFrom:
            - configMapRef:
                name: env-configmap
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
