apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-primary
  template:
    metadata:
      labels:
        app: celery-worker-primary
    spec:
      containers:
        - name: celery-worker-primary
          image: onyxdotapp/onyx-backend-cloud:v0.14.0-cloud.beta.21
          imagePullPolicy: IfNotPresent
          command:
            [
              "celery",
              "-A",
              "onyx.background.celery.versioned_apps.primary",
              "worker",
              "--loglevel=INFO",
              "--hostname=primary@%n",
              "-Q",
              "celery,periodic_tasks",
              "--prefetch-multiplier=1",
              "--concurrency=10",
            ]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onyx-secrets
                  key: redis_password
            - name: ONYX_VERSION
              value: "v0.11.0-cloud.beta.8"
          envFrom:
            - configMapRef:
                name: env-configmap
          volumeMounts:
            - name: vespa-certificates
              mountPath: "/app/certs"
              readOnly: true
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: vespa-certificates
          secret:
            secretName: vespa-certificates
            items:
              - key: cert.pem
                path: cert.pem
              - key: key.pem
                path: key.pem
